### ISSUE TITLE
Why the installation always failed on linux centos?

### ISSUE THREAD

**Issue by danxinju** [Xyene/sphere2cube#2]
I have tried pip install sphere2cube and easy_install sphere2cube, and got the following message:

> Downloading/unpacking sphere2cube
  Downloading sphere2cube-0.1.8.zip (107kB): 107kB downloaded
  Running setup.py (path:/tmp/pip_build_xinju.dan/sphere2cube/setup.py) egg_info for package sphere2cube
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_xinju.dan/sphere2cube/setup.py", line 14, in <module>
        exec (version.read())
      File "<string>", line 1
        __author__ = 'Xyene'
                            ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_xinju.dan/sphere2cube/setup.py", line 14, in <module>

    exec (version.read())

  File "<string>", line 1

    __author__ = 'Xyene'

                        ^

SyntaxError: invalid syntax

**Comment by danxinju** [comment]
My python version is 2.6

**Comment by danxinju** [comment]
Aha, I have copied __author__ = 'Xyene' __version__ = '0.1.8' from version.py to instead of reading version.py in the setup.py.

Now problem fixed!
